# Generated by Django 5.0.6 on 2024-06-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='abilities',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='education',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دیپلم'), (2, 'کاردانی'), (3, 'کارشناسی'), (4, 'کارشناسی ارشد'), (5, 'دکتری')], verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مونث'), (2, 'مذکر')], verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nc',
            field=models.BigIntegerField(verbose_name='nc'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='abilities',
            field=models.CharField(choices=[('piping', 'لوله کشی'), ('building', 'بنا'), ('welder', 'جوشکار'), ('electrician', 'برقکار'), ('plaster', 'گچ کار'), ('facilities', 'تاسیسات'), ('graphist', 'گرافیست'), ('programmer', 'برنامه نویس'), ('photographer', 'عکاس'), ('Cameraman', 'فیلم بردار'), ('editor', 'ویرایشگر'), ('content', 'تولید محتوا'), ('speaker', 'گوینده'), ('kindergarten', 'مهدکودک'), ('translator', 'مترجم عربی'), ('PA', 'پزشک عمومی'), ('specialist', 'پزشک متخصص'), ('psychologist', 'روانشناس'), ('consult', 'مشاوره'), ('dentist', 'دندان پزشک'), ('pharmacist', 'داروساز'), ('nurse', 'پرستار'), ('executive', 'پشتیبان اجرایی'), ('cook', 'آشپز'), ('heavy vehicle', 'راننده ماشین سنگین'), ('pickup truck', 'راننده وانت')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
