# Generated by Django 5.0.6 on 2024-07-01 17:11

import utils.file_path_creator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(upload_to=utils.file_path_creator.make_image_path, verbose_name='profile picture'),
        ),
    ]
