# Generated by Django 5.0.6 on 2024-07-11 09:22

import django_jalali.db.models
import utils.file_path_creator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image_alter_volunteer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='abilities',
            field=models.CharField(choices=[('piping', 'لوله کشی'), ('building', 'بنا'), ('welder', 'جوشکار'), ('electrician', 'برقکار'), ('plaster', 'گچ کار'), ('facilities', 'تاسیسات'), ('graphist', 'گرافیست'), ('programmer', 'برنامه نویس'), ('photographer', 'عکاس'), ('Cameraman', 'فیلم بردار'), ('editor', 'ویرایشگر'), ('content', 'تولید محتوا'), ('speaker', 'گوینده'), ('kindergarten', 'مهدکودک'), ('translator', 'مترجم عربی'), ('PA', 'پزشک عمومی'), ('specialist', 'پزشک متخصص'), ('psychologist', 'روانشناس'), ('consult', 'مشاوره'), ('dentist', 'دندان پزشک'), ('pharmacist', 'داروساز'), ('nurse', 'پرستار'), ('executive', 'پشتیبان اجرایی'), ('cook', 'آشپز'), ('heavy vehicle', 'راننده ماشین سنگین'), ('pickup truck', 'راننده وانت')], default='لوله کشی', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth',
            field=django_jalali.db.models.jDateField(verbose_name='birth day'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دیپلم'), (2, 'کاردانی'), (3, 'کارشناسی'), (4, 'کارشناسی ارشد'), (5, 'دکتری')], null=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='experience_info',
            field=models.TextField(blank=True, null=True, verbose_name='experience info'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مونث'), (2, 'مذکر')], default='مذکر', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], default='مجرد', verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nc',
            field=models.CharField(max_length=10, unique=True, verbose_name='nc'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_path_creator.make_image_path, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='specialist_info',
            field=models.TextField(blank=True, null=True, verbose_name='specialist info'),
        ),
    ]
