# Generated by Django 5.0.6 on 2024-07-11 10:16

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import utils.file_path_creator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_volunteer_abilities_alter_volunteer_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر محل سکونت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('09(\\d{9})$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='volunteer_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.volunteer', verbose_name='اطلاعات داوطلبی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='abilities',
            field=models.CharField(choices=[('piping', 'لوله کشی'), ('building', 'بنا'), ('welder', 'جوشکار'), ('electrician', 'برقکار'), ('plaster', 'گچ کار'), ('facilities', 'تاسیسات'), ('graphist', 'گرافیست'), ('programmer', 'برنامه نویس'), ('photographer', 'عکاس'), ('Cameraman', 'فیلم بردار'), ('editor', 'ویرایشگر'), ('content', 'تولید محتوا'), ('speaker', 'گوینده'), ('kindergarten', 'مهدکودک'), ('translator', 'مترجم عربی'), ('PA', 'پزشک عمومی'), ('specialist', 'پزشک متخصص'), ('psychologist', 'روانشناس'), ('consult', 'مشاوره'), ('dentist', 'دندان پزشک'), ('pharmacist', 'داروساز'), ('nurse', 'پرستار'), ('executive', 'پشتیبان اجرایی'), ('cook', 'آشپز'), ('heavy vehicle', 'راننده ماشین سنگین'), ('pickup truck', 'راننده وانت')], default='لوله کشی', max_length=100, verbose_name='توانایی ها'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر محل سکونت'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دیپلم'), (2, 'کاردانی'), (3, 'کارشناسی'), (4, 'کارشناسی ارشد'), (5, 'دکتری')], null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='experience_info',
            field=models.TextField(blank=True, null=True, verbose_name='سابقه کار جهادی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مونث'), (2, 'مذکر')], default='مذکر', verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], default='مجرد', verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nc',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('09(\\d{9})$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_path_creator.make_image_path, verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='specialist_info',
            field=models.TextField(blank=True, null=True, verbose_name='تخصص'),
        ),
    ]
