# Generated by Django 5.0.6 on 2024-07-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('date_modify', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'document category',
                'verbose_name_plural': 'document categories',
                'db_table': 'document_category',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.documentcategory'),
        ),
    ]
