# Generated by Django 5.0.6 on 2024-07-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_maindata_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindata',
            old_name='eturl',
            new_name='eitaa',
        ),
        migrations.RenameField(
            model_name='maindata',
            old_name='igurl',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='maindata',
            old_name='telurl',
            new_name='telegram',
        ),
    ]
