# Generated by Django 5.0.6 on 2024-07-29 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_eturl_maindata_eitaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_modify',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ آخرین تغییر'),
            preserve_default=False,
        ),
    ]
