# Generated by Django 5.0.6 on 2024-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_date_added_user_date_modify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مونث'), (2, 'مذکر')], default=2, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], default=1, verbose_name='وضعیت تاهل'),
        ),
    ]
