# Generated by Django 4.2.20 on 2025-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_volunteer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ افزودن'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='date_modify',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین تغییر'),
        ),
    ]
