# Generated by Django 5.0.6 on 2025-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_documentcategory_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birth',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
    ]
