# Generated by Django 5.0.6 on 2024-08-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='is valid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentcategory'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='request user'),
        ),
    ]
