# Generated by Django 5.0.6 on 2024-08-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.BigIntegerField(verbose_name='شماره کارت')),
            ],
            options={
                'verbose_name': 'شماره کارت',
                'verbose_name_plural': 'شماره کارت ها',
            },
        ),
    ]
