# Generated by Django 5.0.6 on 2024-08-04 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'در انتظار'), (2, 'در پروسه انجام'), (3, 'در پروسه انجام'), (4, 'در پروسه انجام'), (5, 'در پروسه انجام')], verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_trace_id',
            field=models.UUIDField(unique=True, verbose_name='payment trace id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_time',
            field=models.DateTimeField(verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.PositiveBigIntegerField(verbose_name='میزان پرداخت'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
    ]
