# Generated by Django 5.0.6 on 2024-08-07 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_pay_id_payment_is_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_service_trace_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پیگیری سرویس  پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='معتبر است'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod', verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'در انتظار'), (2, 'در پروسه انجام'), (3, 'در حال انجام'), (4, 'انجام یافته'), (5, 'ناموفق')], verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_trace_id',
            field=models.UUIDField(unique=True, verbose_name='شناسه پیگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_time',
            field=models.DateTimeField(verbose_name='زمان پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
    ]
