# Generated by Django 5.0.6 on 2024-08-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_date_added_alter_payment_date_modify_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcategory',
            options={'verbose_name': 'کتگوری پرداخت', 'verbose_name_plural': 'کتگوری های پرداخت'},
        ),
    ]
