# Generated by Django 5.0.6 on 2024-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_service_trace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_service_trace_id',
            field=models.UUIDField(unique=True, verbose_name='شناسه پیگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_trace_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پیگیری سرویس  پرداخت'),
        ),
    ]
