# Generated by Django 5.0.6 on 2025-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_service_trace_id_and_more'),
        ('payment', '0004_alter_paymentcategory_options'),
    ]

    operations = [
    ]
