# Generated by Django 4.2.20 on 2025-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_merge_20250309_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_service_trace_id',
            field=models.UUIDField(unique=True, verbose_name='شناسه پیگیری سرویس  پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_trace_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پیگیری پرداخت'),
        ),
    ]
