# Generated by Django 5.0.6 on 2024-07-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('date_modify', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
            ],
            options={
                'verbose_name': 'notification category',
                'verbose_name_plural': 'notification categories',
                'db_table': 'notification_category',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیح کوتاه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ')),
                ('is_seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationcategory')),
            ],
        ),
    ]
