# Generated by Django 5.0.6 on 2024-07-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_date_added_notification_date_modify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notificationcategory'),
        ),
    ]
