# Generated by Django 4.2.20 on 2025-03-14 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen_by',
            field=models.ManyToManyField(related_name='seen_notifications', to=settings.AUTH_USER_MODEL, verbose_name='دیده شده توسط'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
