# Generated by Django 5.0.6 on 2024-07-17 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
