# Generated by Django 5.0.6 on 2024-07-30 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('since', models.DateField(verbose_name='تاریخ شروع')),
                ('till', models.DateField(verbose_name='تاریخ اتمام')),
                ('place', models.CharField(max_length=255, verbose_name='مکان')),
                ('number', models.IntegerField(verbose_name='ظرفیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='داوطلبان')),
            ],
            options={
                'verbose_name': 'اردو',
                'verbose_name_plural': 'اردو ها',
            },
        ),
    ]
